# GitLab Pages webapp deployment

pages:
  image: node:latest
  stage: deploy
  script:
    - mkdir .public
    - cp -r * .public
    - mv .public public
    - echo "The app will be deployed to $CI_PAGES_URL"
  artifacts:
    paths:
    - public/
  only:
    - main
